# Generated by Django 4.2.1 on 2023-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_time_step_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='victim',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
