# Generated by Django 4.2.1 on 2023-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_victim_image_victim_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_step',
            name='year',
            field=models.CharField(choices=[('september', '26. September 2014'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default='2014', max_length=10),
        ),
    ]
