# Generated by Django 4.2.1 on 2023-06-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_time_step_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process_Documentation_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('image_alt', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Process_Documentation_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Process_Documentation',
        ),
        migrations.AddField(
            model_name='process_documentation_image',
            name='process_documentation_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.process_documentation_section'),
        ),
    ]
