# Generated by Django 4.2.1 on 2023-06-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_process_documentation_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Seite', 'verbose_name_plural': 'Seiten'},
        ),
        migrations.AlterModelOptions(
            name='process_documentation_image',
            options={'verbose_name': 'Prozess Abschnitt Bild', 'verbose_name_plural': 'Prozess Abschnitt Bilder'},
        ),
        migrations.AlterModelOptions(
            name='process_documentation_section',
            options={'verbose_name': 'Dokumentations Abschnitt', 'verbose_name_plural': 'Dokumentations Abschnitte'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Quelle', 'verbose_name_plural': 'Quellen'},
        ),
        migrations.AlterModelOptions(
            name='source_category',
            options={'verbose_name': 'Quellenkategorie', 'verbose_name_plural': 'Quellenkategorien'},
        ),
        migrations.AlterModelOptions(
            name='time_step',
            options={'verbose_name': 'Zeitpunkt', 'verbose_name_plural': 'Zeitpunkte'},
        ),
        migrations.AlterModelOptions(
            name='victim',
            options={'verbose_name': 'Opfer', 'verbose_name_plural': 'Opfer'},
        ),
        migrations.AddField(
            model_name='process_documentation_image',
            name='big',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='victim',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='victim',
            name='birth_city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='victim',
            name='birth_year',
            field=models.IntegerField(default=2000),
        ),
    ]
