# Generated by Django 4.2.1 on 2023-06-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='prename',
            field=models.CharField(default='', max_length=50),
        ),
    ]
