# Generated by Django 4.2.1 on 2023-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_victim_prename'),
    ]

    operations = [
        migrations.CreateModel(
            name='moreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='source',
            name='category',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='birth_city',
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(choices=[('home', 'Gewaltsames Verschwinden'), ('school', 'Lehramtschulen'), ('ayotzinapa', 'Ayotzinapa'), ('students', 'Studenten'), ('source', 'Quellen'), ('contact', 'Kontakt'), ('impressum', 'Impressum'), ('legal', 'Data protection')], default='home', max_length=20),
        ),
        migrations.DeleteModel(
            name='Process_Documentation_Image',
        ),
        migrations.DeleteModel(
            name='Process_Documentation_Section',
        ),
        migrations.DeleteModel(
            name='Source_Category',
        ),
    ]
